### PR TITLE
Add EMA Vector Quantizer

### PR DESCRIPTION
**Pull request by tgisaturday**
Hi, I implemented EMA(Exponential Moving Average) version of Vector Quantizer following VectorQuantizer2 from the original repo. I also included original sonnet-style EMAVectorQuantizer as SonnetEMAVectorQuantizer. I also added EMAVQ in vqgan.py. Please ping me if you have any questions. Thank you.

### CODE REVIEW

**Comment by rromb** [comment]
Very nice, thank you. Is my understanding correct that `EMAVectorQuantizer` and `SonnetEMAVectorQuantizer` both apply the same codebook learning algorithm and forward pass (i.e. the one from the [sonnet-vqvae](https://github.com/deepmind/sonnet/blob/v1/sonnet/python/modules/nets/vqvae.py) implementation)? Should we merge them into a single class?

**Comment by tgisaturday** [comment]
> Very nice, thank you. Is my understanding correct that `EMAVectorQuantizer` and `SonnetEMAVectorQuantizer` both apply the same codebook learning algorithm and forward pass (i.e. the one from the [sonnet-vqvae](https://github.com/deepmind/sonnet/blob/v1/sonnet/python/modules/nets/vqvae.py) implementation)? Should we merge them into a single class?

Yes. sonnet one is original EMAVQ from VQVAE2 and the other one follows taming transformer style. I'll make new PR with refined EMAVQ.

**Comment by tgisaturday** [comment]
> > Very nice, thank you. Is my understanding correct that `EMAVectorQuantizer` and `SonnetEMAVectorQuantizer` both apply the same codebook learning algorithm and forward pass (i.e. the one from the [sonnet-vqvae](https://github.com/deepmind/sonnet/blob/v1/sonnet/python/modules/nets/vqvae.py) implementation)? Should we merge them into a single class?
> 
> Yes. sonnet one is original EMAVQ from VQVAE2 and the other one follows taming transformer style. I'll make new PR with refined EMAVQ.

@rromb Just added newest EMA VQ and removed sonnet ones. I've tested EMA VQ my VAEs but not 100% sure it will work with VQGANs.

**Comment by rromb** [comment]
Awesome, let's find out how it works with VQGANs :)

**Pull request merged**
