### PR TITLE
add custom dataset and instruction for training on a custom dataset

### PR DESCRIPTION
**Pull request by rom1504**
Hi,
I created a custom dataset loader taking as input jpg files in a folder.
I think this makes it easy for people discovering this repo to train on a custom dataset.
Tell me what you think.
This was useful for me to start training my own VQGAN
Thanks for this awesome paper and clean repo!

### CODE REVIEW

**Comment by ChristianFJung** [comment]
Big fan of this. Definitely, an advocate that this should be merged. 


@rom1504 only thing I'm wondering is where you set the # of epochs? Kinda going crazy looking for it.

**Comment by rom1504** [comment]
@ChristianFJung Hi, the cli is passing arguments to pytorch lightning Trainer class, so you can check them out there https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.html#pytorch_lightning.trainer.trainer.Trainer
The parameter you want is `--max_epochs` (the default is 1000)
On the same topic, you may want to use the `--precision 16` option to enable 16-bit precision (lower the ram usage and allow increasing the batch size, they use it in the paper)

**Comment by rromb** [comment]
Hi! 
Thanks for the suggestion,  we're currently working on an update for the paper and code and will probably include this :)

**Comment by pesser** [comment]
Thanks, that's awesome! :rocket:

**Comment by ChristianFJung** [comment]
@rom1504 what's the simplest way to sample a custom model like this?

**Comment by rom1504** [comment]
@ChristianFJung there are various ways:
* Train a transformer with this repo (that's the method used in the paper). That'll enable you to do unconditional sampling and class based sampling
* train a dalle model using dalle pytorch, that'll enable you to do text to image
* use the clip + vqgan back propagation (listed in the readme of this readme), that can be used to to text to image also

The last way is the quickest to setup, other ways are more powerful but require to train other models.

**Comment by hjq133** [comment]
> @ChristianFJung there are various ways:
> 
> * Train a transformer with this repo (that's the method used in the paper). That'll enable you to do unconditional sampling and class based sampling
> * train a dalle model using dalle pytorch, that'll enable you to do text to image
> * use the clip + vqgan back propagation (listed in the readme of this readme), that can be used to to text to image also
> 
> The last way is the quickest to setup, other ways are more powerful but require to train other models.

Thank you, can you share the config file to train an unconditional transformer on the Imagenet ? I don't know if there is anything wrong with my config file. report in the #104

**Comment by navuboy** [comment]
where to set the f value for the custom data training?

**Comment by Blackkinggg** [comment]
> > @ChristianFJung there are various ways:
> > ```
> > * Train a transformer with this repo (that's the method used in the paper). That'll enable you to do unconditional sampling and class based sampling
> > 
> > * train a dalle model using dalle pytorch, that'll enable you to do text to image
> > 
> > * use the clip + vqgan back propagation (listed in the readme of this readme), that can be used to to text to image also
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The last way is the quickest to setup, other ways are more powerful but require to train other models.
> 
> how to train transformer

I have the same question， have you knew it？

**Pull request merged**
